### ISSUE TITLE
ERROR: /usr/bin/nvidia-container-runtime: unmarshal OCI spec file: (Centos7)

### ISSUE THREAD

**Issue by smogsy** [NVIDIA/nvidia-container-runtime#105] opened 2020-06-01 11:26 UTC
This is a Bug Report/advice post

OS CentOS7
Docker 1.13.1
nvidia-container-runtime - newest
NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2
Card Quadro P2000

**Issue:**
command: docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi

```
ERROR: /usr/bin/nvidia-container-runtime: unmarshal OCI spec file: json: cannot unmarshal array into Go struct field Process.capabilities of type specs.LinuxCapabilities
/usr/bin/docker-current: Error response from daemon: containerd: container not started.
```

**What am im trying to do:**
trying to test run docker seeing nvidia card correctly.
docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi

Nvidia-container-runtime has been added to service file.

**Logs**
```
2020/06/01 12:11:37 Running /usr/bin/nvidia-container-runtime
2020/06/01 12:11:37 Using bundle file: /var/run/docker/libcontainerd/7443682205db285fc37af7e2c80bc55a30fa6023e5d8c221af6b6741a3875d70/config.json
2020/06/01 12:11:37 ERROR: unmarshal OCI spec file: json: cannot unmarshal array into Go struct field Process.capabilities of type specs.LinuxCapabilities
2020/06/01 12:11:37 Running /usr/bin/nvidia-container-runtime
2020/06/01 12:11:37 Command is not "create", executing runc doing nothing
2020/06/01 12:11:37 Looking for "docker-runc" binary
2020/06/01 12:11:37 "docker-runc" binary not found
2020/06/01 12:11:37 Looking for "runc" binary
2020/06/01 12:11:37 ERROR: find runc path: exec: "runc": executable file not found in $PATH
```

docker version
```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64
 Experimental:    false

```
nvidia versions
nvidia-xconfig-branch-440-440.64.00-1.el7.x86_64
nvidia-container-runtime-3.2.0-1.x86_64
libnvidia-container-tools-1.1.1-1.x86_64
nvidia-driver-branch-440-cuda-libs-440.64.00-1.el7.x86_64
nvidia-libXNVCtrl-devel-440.64.00-1.el7.x86_64
nvidia-container-toolkit-1.1.1-2.x86_64
yum-plugin-nvidia-0.5-1.el7.noarch
nvidia-driver-branch-440-NvFBCOpenGL-440.64.00-1.el7.x86_64
nvidia-modprobe-branch-440-440.64.00-1.el7.x86_64
nvidia-driver-branch-440-cuda-440.64.00-1.el7.x86_64
nvidia-settings-440.64.00-1.el7.x86_64
nvidia-driver-branch-440-devel-440.64.00-1.el7.x86_64
kmod-nvidia-latest-dkms-440.64.00-1.el7.x86_64
nvidia-persistenced-branch-440-440.64.00-1.el7.x86_64
libnvidia-container1-1.1.1-1.x86_64
nvidia-driver-branch-440-libs-440.64.00-1.el7.x86_64
nvidia-libXNVCtrl-440.64.00-1.el7.x86_64
nvidia-driver-branch-440-NVML-440.64.00-1.el7.x86_64
nvidia-driver-branch-440-440.64.00-1.el7.x86_64

ive tried adding /usr/libexec/docker/docker-runc-current to my user path no luck

**other notes:**
should they have paths?
whereis docker-runc
docker-runc:
$ whereis runc
runc:
$

**Comment by klueska** [comment] 2020-06-01 13:03
Your version of docker is 1.13.1

This is a really old version of docker that the `nvidia-container-runtime` may not support directly.

Is it possible for you to upgrade your version of docker?
https://docs.docker.com/engine/install/centos/

**Comment by smogsy** [comment] 2020-06-01 13:36
ill have a look, as this is CentOS packages maybe be old in general.

**Comment by zvonkok** [comment] 2020-06-01 13:51
@klueska @smogsy CentOS and RHEL have an own docker that can execute prestart hooks  without registering the nvidia-container-runtime. 

In CentOS7 and RHEL7 we only need the nvidia-container-runtime-hook package. 

The hook activation files changed in specific versions of `runc`. Which `runc` version are you running? How does the oci-nvidia-hook.json file looks like? 

Create the following `oci-nvidia-hook.json` for older `runc` versions and try again: 

```
# cat <<'EOF' >> /usr/share/containers/oci/hooks.d/oci-nvidia-hook.json
{ 
     "hasbindmounts": true,  
     "hook": "/usr/bin/nvidia-container-runtime-hook",  
     "stage": [ "prestart" ]
}
EOF
--

**Comment by smogsy** [comment] 2020-06-01 13:56
@zvonkok 
 docker-runc --version
runc version 1.0.0-rc2
commit: 9c3c5f853ebf0ffac0d087e94daef462133b69c7
spec: 1.0.0-rc2-dev

`{
    "version": "1.0.0",
    "hook": {
        "path": "/usr/bin/nvidia-container-toolkit",
        "args": ["nvidia-container-toolkit", "prestart"],
        "env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ]
    },
    "when": {
        "always": true,
	"commands": [".*"]
    },
    "stages": ["prestart"]
}`

**Comment by klueska** [comment] 2020-06-01 14:02
Hmm. The `nvidia-container-runtime-hook` package reached end of life about a year and a half ago. The new architecture of `nvidia-container-toolkit` and `nvidia-docker2` doesn't include it anymore.

To remain backwards compatible, the `nvidia-container-runtime` package now creates a symlink from `nvidia-container-runtime-hook` to `nvidia-container-toolkit` (which is the name of the binary that replaced it).

So maybe you meant to say that the package he needed to include was `nvidia-container-runtime`? Otherwise he would be getting very old versions of the tools.

**Comment by smogsy** [comment] 2020-06-01 14:22
@klueska @zvonkok 
here is a list of packages that was installed
    - libnvidia-container-tools (required by below runtime package when trying to install runtime)
    - nvidia-container-runtime
    - kernel-headers
    - kernel-devel
    - "yum-plugin-nvidia-{{ magiq_yum_nvidia_plugin_version }}"
    - "nvidia-driver-branch-{{ magiq_nvidia_drivers_branch }}"
    - "nvidia-driver-branch-{{ magiq_nvidia_drivers_branch }}-cuda"
    - "nvidia-driver-branch-{{ magiq_nvidia_drivers_branch }}-cuda-libs"
    - cuda-drivers

**Comment by zvonkok** [comment] 2020-06-01 14:30
You need to install `nvidia-container-toolkit` @klueska is right, the hook rpm is deprecated.  Remove the nvidia-container-runtime.

**Comment by zvonkok** [comment] 2020-06-01 14:32
The `/usr/share/containers/oci/hooks.d/oci-nvidia-hook.json` should have been updated with 
```
{
    "version": "1.0.0",
    "hook": {
        "path": "/usr/bin/nvidia-container-toolkit",
        "args": ["nvidia-container-toolkit", "prestart"],
        "env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ]
    },
    "when": {
        "always": true,
	"commands": [".*"]
    },
    "stages": ["prestart"]
}
```

**Comment by zvonkok** [comment] 2020-06-01 14:35
The key part is the `/usr/bin/nvidia-container-toolkit` and you need to install the SELinux policy if you are running with SELinux. If not ignore it. 

This is the way you would run it with SELinux and policy applied (Policy:  https://github.com/NVIDIA/dgx-selinux ) 
```
docker run  --user 1000:1000 --security-opt=no-new-privileges --cap-drop=ALL \ 
              --security-opt label=type:nvidia_container_t    \
  docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1
```

**Comment by smogsy** [comment] 2020-06-01 15:40
@zvonkok 
as mentioned previously I have the following installed which covers nvidia-container-toolkit from my view.
my file looks like this:
{
    "version": "1.0.0",
    "hook": {
        "path": "/usr/bin/nvidia-container-toolkit",
        "args": ["nvidia-container-toolkit", "prestart"],
        "env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ]
    },
    "when": {
        "always": true,
	"commands": [".*"]
    },
    "stages": ["prestart"]
}




`
cuda-drivers.x86_64           440.64.00-1                 @nvidia_cuda_compute
kmod-nvidia-latest-dkms.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
libnvidia-container-tools.x86_64
                              1.1.1-1                     @libnvidia-container
libnvidia-container1.x86_64   1.1.1-1                     @libnvidia-container
nvidia-container-runtime.x86_64
                              3.2.0-1                     @nvidia_container_runtime
nvidia-container-toolkit.x86_64
                              1.1.1-2                     @nvidia_container_runtime
nvidia-driver-branch-440.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-driver-branch-440-NVML.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-driver-branch-440-NvFBCOpenGL.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-driver-branch-440-cuda.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-driver-branch-440-cuda-libs.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-driver-branch-440-devel.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-driver-branch-440-libs.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-libXNVCtrl.x86_64      3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-libXNVCtrl-devel.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-modprobe-branch-440.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-persistenced-branch-440.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-settings.x86_64        3:440.64.00-1.el7           @nvidia_cuda_compute
nvidia-xconfig-branch-440.x86_64
                              3:440.64.00-1.el7           @nvidia_cuda_compute
yum-plugin-nvidia.noarch      0.5-1.el7                   @nvidia_cuda_compute`

**Comment by smogsy** [comment] 2020-06-02 06:41
@klueska @zvonkok 
i tried to remove the nvidia-container-runtime suggested by @zvonkok, but that broke things further

here is what bin files i have and their relationships
-rwxr-xr-x   1 root root      31K Feb 26 16:50 nvidia-bug-report.sh
-rwxr-xr-x   1 root root      43K May 19 16:16 nvidia-container-cli
-rwxr-xr-x   1 root root     2.2M May 18 13:02 nvidia-container-runtime
lrwxrwxrwx   1 root root       33 May 22 11:35 nvidia-container-runtime-hook -> /usr/bin/nvidia-container-toolkit

-rwxr-xr-x   1 root root     2.3M May 19 16:03 nvidia-container-toolkit
-rwxr-xr-x   1 root root      75K Feb 26 16:15 nvidia-cuda-mps-control
-rwxr-xr-x   1 root root      56K Feb 26 16:15 nvidia-cuda-mps-server
-rwxr-xr-x   1 root root     245K Feb 26 16:04 nvidia-debugdump
-rwsr-xr-x   1 root root     142K Feb 27 23:33 nvidia-modprobe
-rwxr-xr-x   1 root root     216K Feb 27 23:33 nvidia-persistenced
-rwxr-xr-x   1 root root     751K Feb 27 23:40 nvidia-settings
-rwxr-xr-x   1 root root     522K Feb 26 16:06 nvidia-smi

**Comment by smogsy** [comment] 2020-06-02 09:18
after testing againist a working server with setup

sudo docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi fails on both
sudo docker run --rm nvidia/cuda nvidia-smi - fails only on new server.

Both running 1.13.1 docker
working server running CentOS 7.6
other Server running CentOS 7.7

working server is running
1.0.5.2 toolkit & container, runtime 3.1

other server is running 1.1.1-1 container 3.2

sudo docker run --rm nvidia/cuda nvidia-smi
container_linux.go:235: starting container process caused "process_linux.go:339: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: could not decode OCI spec: json: cannot unmarshal array into Go struct field Process.process.capabilities of type main.LinuxCapabilities\\n\""
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "process_linux.go:339: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: could not decode OCI spec: json: cannot unmarshal array into Go struct field Process.process.capabilities of type main.LinuxCapabilities\\n\"".
ERRO[0000] error getting events from daemon: context canceled

**Comment by klueska** [comment] 2020-06-02 11:41
I think I got to the bottom of it:

The version of `docker-runc` that is installed by default on centos7 is `1.0.0-rc2` which uses OCI spec `1.0.0-rc2-dev`:
```
# /usr/bin/docker-runc --version
runc version 1.0.0-rc2
commit: 66aedde759f33c190954815fb765eedc1d782dd9
spec: 1.0.0-rc2-dev
```

This is a prerelease of the OCI spec, which defines the `capabilities` section of a `process` configuration to be a flat list of capabilities (e.g. `SYS_ADMIN`, `SYS_PTRACE`, `SYS_RAWIO`, etc.)
https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc2/config.md#process-configuration

By the time the official 1.0.0 version of the OCI spec came out, the `capabilities` section of a `process` configuration was expanded to  include embedded fields for `effective`, `bounding`, `inheritable`, `permitted` and `ambient` (each of which can contain a flat list of capabilities of the form `SYS_ADMIN`, `SYS_PTRACE`, `SYS_RAWIO`, etc.)
https://github.com/opencontainers/runtime-spec/blob/v1.0.0/config.md#linux-process

The problem is that version 1.1.0 of the `nvidia-container-toolkit` now inspects the `capabilities` section of a `process` configuration and assumes it is in the format of OCI spec 1.0.0.

I don't believe NVIDIA has plans of supporting OCI spec v1.0.0-rc2, so you will either need to:
1) upgrade your version of docker
2) downgrade your version of nvidia-container-toolkit

 It might also be worth talking with someone at Red Hat (/cc @zvonkok) to see if they can update their  default version of `docker-runc` to `v1.0.0` to avoid this problem in the future.

**Comment by smogsy** [comment] 2020-06-02 11:46
thank you ill try that

to confirm ive detailed a working & non -working system for your & my information
| section  |      not working      |  working |
|----------|:-------------:|------:|
| docker|   1.13.1, build 7f2769b/1.13.1| 1.13.1, build b2f74b2/1.13.1|
| nvidia-smi|    440.64  |   440.31 |
| cuda | 10.2| 10.2 |
| CentOS| 7.7.1908| 7.6.1810 |
| oci-systemd-hook| 0.20 | 0.1.18 | 
| libnvidia-container-tools | 1.1.1-1 | 1.0.5-1 
| libnvidia-container1 | 1.1.1-1 | 1.0.5-1
| libnvidia-container-runtime | 3.2.0-1 | 3.1.4-1
| libnvidia-container-toolkit | 1.1.1-2 | 1.0.5-1
| yum-plugin | 0.5-1.el7 | 0.3-1.el7
| runc | 1.0.0-rc2 | 1.0.0-rc2

**Comment by klueska** [comment] 2020-06-02 12:01
```
yum install -y nvidia-container-toolkit-1.0.5-2.x86_64
```

**Comment by smogsy** [comment] 2020-06-02 12:05
@klueska  
* will i need to lock the runtime to older version too? as it seems to want to reinstall 1.1.1 even though 1.0.5 is present

**Comment by klueska** [comment] 2020-06-02 12:21
As zvonko mentioned before, you don't need the runtime -- just remove it.

**Comment by smogsy** [comment] 2020-06-02 12:25
@klueska  as yes, retested & works :)
Your a star!

**Comment by klueska** [comment] 2020-06-02 19:10
After some internal discussions. We decided to push out a patch release to fix this issue. Should be available in the next couple of days.

**Comment by smogsy** [comment] 2020-06-02 21:27
Would you mind letting me know the version number going forward with the patch applied. 
(Once you know) many thanks again much appreciated!

@klueska @zvonkok

**Comment by klueska** [comment] 2020-06-04 10:18
The PR is merged, and will be included in the next patch release (which I will try and push out later today): https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/merge_requests/9

the version of the patch release will be 1.1.2.

**Comment by klueska** [comment] 2020-06-04 14:02
OK, Patch release is live.

**Comment by smogsy** [comment] 2020-06-05 07:44
Thankyou @klueska will be testing it today :)

**Comment by klueska** [comment] 2020-06-05 10:15
The change is generic.
It handles all versions from 1.0.0-rc1 through the current version of the OCI spec.

**Closed by klueska** 2020-06-05 10:15 UTC
