### ISSUE TITLE
Incompatible with docker.io update on ubuntu: "error adding seccomp filter rule for syscall clone3: permission denied: unknown"

### ISSUE THREAD

**Issue by dannf** [NVIDIA/nvidia-container-runtime#157] opened 2021-10-26 15:25 UTC
Ubuntu is in the progress of updating the docker.io version in 20.04. We've discovered that the `nvidia-container-runtime` provided for Ubuntu 20.04 is incompatible with this update. This bug was reported in Ubuntu [here](https://launchpad.net/bugs/1948361).

```
$ sudo nvidia-docker run \
>          --shm-size=1g \
>          --ulimit memlock=-1 \
>          --ulimit stack=67108864 \
>          --rm nvcr.io/nvidia/tensorflow:21.07-tf1-py3 -- \
>          mpiexec \
>          --bind-to socket \
>          --allow-run-as-root \
>          -np 8 \
>          python -u /workspace/nvidia-examples/cnn/resnet.py \
>          --layers=50 \
>          --precision=fp16 \
>          --batch_size=256 \
>          --num_iter=300 \
>          --iter_unit=batch \
>          --display_every=300
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall clone3: permission denied: unknown.
```

**Comment by dannf** [comment] 2021-11-01 15:32
> The last log message is from [here](https://gitlab.com/nvidia/container-toolkit/container-runtime/-/blob/v3.5.0/cmd/nvidia-container-runtime/nvcr.go#L62) and what follows is a [`syscall.Exec` to `/usr/sbin/runc`](https://gitlab.com/nvidia/container-toolkit/container-runtime/-/blob/v3.5.0/pkg/oci/runtime_exec.go#L71).
> 
> Was a `/var/log/nvidia-container-toolkit.log` file also generated? 

no

> I wouldn't expect so as we only trigger the `nvidia-container-cli` if the `NVIDIA_VISIBLE_DEVICES` envvar is set (e.g. to "all") in the container and this would not be the case for the `docker.io/ubuntu:latest` image you are using. Unless this is the case, the log seems to indicate that the issue is being caused when Execing into the `/usr/sbin/runc` binary. Could we confirm that this is the same `runc` that is being used when invoking the `docker` command directly?

Yes, there is only one runc installed, the one from the Ubuntu proposed archive. I'm not sure how to generate a log that *provies* this, so I explicitly defined a new runtime profile (`runcx`) that explicitly points at `/usr/sbin/runc`, and used `--runtime runcx` to verify:

```
root@dannf-docker-focal:~# docker run --runtime runcx --rm -it docker.io/ubuntu:latest /bin/true
root@dannf-docker-focal:~#
```

**Comment by elezar** [comment] 2021-11-02 20:52
@dannf would it be possible to capture the incoming OCI spec (`config.json`) and attach it to this issue? There were seccomp flags added to the `v1.0.2` OCI runtime spec and since the `nvidia-container-runtime` explicitly pulls in the `v1.0.1` spec these added fields may be dropped when we update the spec to inject the container hook. I will also check if I can confirm this tomorrow.

**Comment by dannf** [comment] 2021-11-02 20:57
@elezar happy to if you can tell me how :) My `docker` skills are pretty basic.

**Comment by elezar** [comment] 2021-11-03 09:47
One option would be to add a shim runtime that copies the incoming spec, but that's a bit too involved. I just confirmed the following steps:

1. start a docker container (note this keeps it running): `docker run --rm -it docker.io/ubuntu:latest bash`
2. get the ID of the container that was just started: `docker ps --no-trunc`
3. Copy the config file from `/run/containerd/io.containerd.runtime.v1.linux/moby/${CONTAINER_ID}/config.json`

Assuming you have just one container running you should be able to use:
```
sudo cp /run/containerd/io.containerd.runtime.v1.linux/moby/$(docker ps --no-trunc -q)/config.json ~/copied-config.json
```

One caveat is that these instructions are correct for my docker version:
```
docker --version
Docker version 18.09.2, build 6247962
```
(but does also seem correct for Docker `19.03.4` as shown [here](https://stackoverflow.com/questions/54303822/getting-runc-config-json-from-docker-container))

**Comment by dannf** [comment] 2021-11-03 14:16
Thanks - here it is (piped through `jq`):
[config.json.jq.txt](https://github.com/NVIDIA/nvidia-container-runtime/files/7468171/config.json.jq.txt)

**Comment by elezar** [comment] 2021-11-03 16:06
Thanks for that @dannf. I implemented a simple test locally where I load the spec as the `nvidia-container-runtime` would and write it out again with no modification. The input and output file then differ:
```
✗ diff -w test/input/config.with-clone.json test/output/config.with-clone.json
753,754c753
<           "action": "SCMP_ACT_ERRNO",
<           "errnoRet": 38
---
>                     "action": "SCMP_ACT_ERRNO"
```
with the "modified" file not containing the `errnoRet` specification. (added in [this commit](https://github.com/opencontainers/runtime-spec/commit/3bfcde28eab5d7e107ddd3771fc92399332932a8)) and was not present in the [`v1.0.1`](https://github.com/opencontainers/runtime-spec/blob/v1.0.1/specs-go/config.go) of the OCI spec that we consume (nor in the latest `v1.0.2` release).

I have repeated the same test with a version of the code that uses commit `a3c33d663ebc` of the runtime spec and then these fields are not replaced. Would you be open to testing a pre-release package if I publish it in the next day or two?

**Comment by dannf** [comment] 2021-11-03 19:08
> I have repeated the same test with a version of the code that uses commit `a3c33d663ebc` of the runtime spec and then these fields are not replaced. Would you be open to testing a pre-release package if I publish it in the next day or two?

Sure

**Comment by elezar** [comment] 2021-11-03 21:00
I will get to publishing `-rc.2` versions of our upcoming packages to our experimental repos tomorrow. I did however realise that the dependency has already been updated in our GitHub repo, so we could test this now to reduce the delay:

For now you should be able to run:
```
GOPATH=${HOME}/bin go install github.com/NVIDIA/nvidia-container-toolkit/cmd/nvidia-container-runtime@dd5c0a94ad59cd3fab3c4b844810f35e9664cb81
```
This should create a `${HOME}/bin/nvidia-container-runtime` executable which is using the [updated OCI spec](https://github.com/opencontainers/runtime-spec/tree/1c3f411f041711bbeecf35ff7e93461ea6789220) (although not the current `HEAD`).

If you prefer to build the binary from source you should be able to clone the repo and run:
```
make docker-cmd-nvidia-container-runtime
```
to generate the binary using a docker file.

You should be able to specify this binary as runtime for `docker` in the same way as you did for your `runcx` in your earlier tests.

**Comment by dannf** [comment] 2021-11-04 22:26
The new n-c-r seems to work, thanks @elezar for the fix!

I created an `/etc/docker/daemon.json` entry for both the current version (`nvidia`) and the new go-installed one (`nvidia-new`) to do a controlled comparison:

```
root@dannf-docker-focal:~# docker run --runtime nvidia --rm -it docker.io/ubuntu:latest /bin/true
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall clone3: permission denied: unknown.
ERRO[0000] error waiting for container: context canceled 
```

```
root@dannf-docker-focal:~# docker run --runtime nvidia-new --rm -it docker.io/ubuntu:latest /bin/true
root@dannf-docker-focal:~# echo $?
0
```

Just a heads-up that the updated Ubuntu container stack has now been released into our updates repository, so users of Ubuntu `docker` w/ `nvidia-container-runtime` who install a new system - or upgrade an existing one - will suffer from this issue until the new `n-c-r` is available.

**Comment by elezar** [comment] 2021-11-05 11:00
Thanks for confirming that this addresses the problem. I am working on getting our packages released (at least to our `experimental` repositories) with this fix so that users that run into this can install the `1.6.0~rc.2` packages. These will be promoted to stable in the coming days.

**Comment by niark567** [comment] 2021-11-05 13:36
I encounter the same issue here using Ubuntu 20.04 after updating (today).
I don't have nvidia-container-runtime, nvidia-container-toolkit nor nvidia-docker2 installed but I indeed have the nvidia driver installed and running.
Docker crashes container start with the same error (default runtime) after upgrading the following packages (worked fine previously) :
- `runc:amd64 1.0.0~rc95-0ubuntu1~20.04.2 1.0.1-0ubuntu2~20.04.1`
- `containerd:amd64 1.5.2-0ubuntu1~20.04.3 1.5.5-0ubuntu3~20.04.1`
- `docker.io:amd64 20.10.7-0ubuntu1~20.04.2 20.10.7-0ubuntu5~20.04.1`
- `nvidia-driver-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu`
- `libnvidia-extra-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `libnvidia-gl-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `libnvidia-common-470:all 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `nvidia-dkms-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `nvidia-kernel-source-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `nvidia-kernel-common-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `libnvidia-decode-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `libnvidia-compute-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `nvidia-compute-utils-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `libnvidia-encode-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `nvidia-utils-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `xserver-xorg-video-nvidia-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `libnvidia-ifr1-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `libnvidia-fbc1-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`
- `libnvidia-cfg1-470:amd64 470.57.02-0ubuntu1 470.82.01-0ubuntu1`

**Comment by elezar** [comment] 2021-11-05 13:51
@niark567 your issue seems to be that our `runc` version is not new enough to support the fields that docker is adding to the OCI spec. Please update `runc` and try again.

Note, this has nothing to do with the NVIDIA driver packages.

**Comment by niark567** [comment] 2021-11-05 14:11
ok, thanks @elezar.
I look for a solution in this way.
Using the nvidia runtime (after installing it) leads to the same error (not surprising since it seems to rely on runc).
FYI my runc binary is provided by the official docker package "containerd.io" (v1.4.11-1 from https://download.docker.com/linux/ubuntu focal/stable amd64).

**Comment by elezar** [comment] 2021-11-05 15:22
@dannf I have published updated `-rc.2` packages to our experimental repo. The one that would contain this fix specifically is:
```
nvidia-container-toolkit=1.6.0~rc.2-1
```
which should be pulled in when installing `nvidia-docker2=2.7.0~rc.2` or `nvidia-container-runtime=3.6.0~rc.2`.

Instructions are [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit).

@niark567 if your intent is not to make GPUs available in a containerized environment you should not be using the `nvidia-container-runtime`.

**Comment by alexiaizenberg** [comment] 2021-11-05 17:04
@elezar Thank you, pulled the latest packages and it is working now.

**Comment by girgink** [comment] 2021-11-05 22:42
The same issue exists with the latest L4T 32.6.1 release for NVIDIA Jetson AGX:

```
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall clone3: permission denied: unknown.
ERRO[0001] error waiting for container: context canceled
```

**Comment by maximemoreillon** [comment] 2021-11-07 00:46
> @dannf I have published updated `-rc.2` packages to our experimental repo. The one that would contain this fix specifically is:
> 
> ```
> nvidia-container-toolkit=1.6.0~rc.2-1
> ```
> 
> which should be pulled in when installing `nvidia-docker2=2.7.0~rc.2` or `nvidia-container-runtime=3.6.0~rc.2`.
> 
> Instructions are [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit).
> 
> @niark567 if your intent is not to make GPUs available in a containerized environment you should not be using the `nvidia-container-runtime`.

Sorry if it's not entirely related but the instructions provided yielded the following error:

```
The following packages have unmet dependencies:
 nvidia-docker2 : Depends: nvidia-container-toolkit (>= 1.6.0~rc.2-1) but 1.5.1-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Any idea how to fix this?

**Comment by jgardynik** [comment] 2021-11-07 11:21
It doesn't look like arm64 experimental has the RC packaged. Can we get this fixed? I have a broken Jetson now because Docker got upgraded to v20 due to a lack of dependency restraints. 

`root@Jetson:/var/cache# apt policy nvidia-container-toolkit
nvidia-container-toolkit:
  Installed: 1.0.1-1
  Candidate: 1.5.1-1
  Version table:
     1.5.1-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/arm64  Packages
        500 https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/arm64  Packages
     1.5.0-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/arm64  Packages
     1.4.2-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/arm64  Packages
     1.4.1-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/arm64  Packages
     1.4.0-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/arm64  Packages
     1.3.0-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/arm64  Packages
     1.3.0~rc.2-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/arm64  Packages
     1.3.0~rc.1-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/arm64  Packages
     1.2.1-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/arm64  Packages
     1.2.0-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/arm64  Packages
     1.1.2-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/arm64  Packages
     1.1.1-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/arm64  Packages
     1.1.0-1 500
        500 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/arm64  Packages
 *** 1.0.1-1 500
        500 https://repo.download.nvidia.com/jetson/common r32.6/main arm64 Packages
        100 /var/lib/dpkg/status
`

**Comment by elezar** [comment] 2021-11-08 06:36
@jgardynik I will look into the missing arm packages.

Note, that if you're looking to use the embedded GPUs in Jetson devices, these packages currently have a different release process, and we are working at addressing this.

For the time being you can downgrade `docker.io` (and possibly `containerd`) as a workaround.

**Comment by elezar** [comment] 2021-11-08 06:40
@maximemoreillon please open a new issue with the behaviour that you're seeing.

**Comment by jgardynik** [comment] 2021-11-08 16:53
Yeah, I was the one who posted that workaround because a whole bunch of people are likely to run into this Docker debacle since the update doesn't stop itself despite not being compatible.

What do you mean about a different release process for Jetson? Why can't I install them the same way I install any other package via dpkg or apt? I certainly _hope_ I don't have to wait for Jetpack 5 to come out, which has already been pushed back once and currently has a release date of the middle of next year (if we're lucky). That's another giant mess, since it's upgrading to an LTS version that will be halfway through its standard support lifecycle and another LTS will already be out by the time it releases. But I digress.

**Comment by elezar** [comment] 2021-11-09 11:41
> What do you mean about a different release process for Jetson? Why can't I install them the same way I install any other package via dpkg or apt? I certainly hope I don't have to wait for Jetpack 5 to come out, which has already been pushed back once and currently has a release date of the middle of next year (if we're lucky). That's another giant mess, since it's upgrading to an LTS version that will be halfway through its standard support lifecycle and another LTS will already be out by the time it releases. But I digress.

We are working on getting updated packages out for Jetson to address this issue outside of the Jetpack releases.

**Comment by girgink** [comment] 2021-11-09 11:45
Thanks @elezar. Meanwhile I confirm that downgrading docker.io to 20.10.7-0ubuntu1~18.04.2 solves the issue temporarily for JetPack 4.6 (L4T 32.6.1).

**Comment by pommedeterresautee** [comment] 2021-11-09 12:07
Just for confirmation, updating to the experimental version fixed it (Ubuntu 21.04).

**Comment by emmenlau** [comment] 2021-11-09 12:59
Also confirmed that update to experimental fixed it (Ubuntu 20.04). Two thumbs up! Would be nice if this could be in a non-experimental soon...

**Comment by caballeto** [comment] 2021-11-09 16:56
@emmenlau could you provide some commands on how to install "experimental" release? Will very much appreciate it, thanks.

**Comment by alexiaizenberg** [comment] 2021-11-09 17:00
> 
> 
> @emmenlau could you provide some commands on how to install "experimental" release? Will very much appreciate it, thanks.

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit

**Comment by lgg** [comment] 2021-11-09 17:46
For ubuntu 20 helped:

```
uname -a
Linux ml-prod 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

* add experimental repo: `curl -s -L https://nvidia.github.io/nvidia-container-runtime/experimental/$distribution/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list`
* `sudo apt-get update`
* `sudo apt-get install -y nvidia-docker2`
* `sudo systemctl restart docker`

source: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit

**Comment by paroque28** [comment] 2021-11-09 20:45
@elezar , think fix doesn't work for 18.04.

See:
```
docker run --runtime nvidia -it myimage
docker: Error response from daemon: OCI runtime create failed: flag provided but not defined: -console-socket: unknown.
ERRO[0000] error waiting for container: context canceled
```

```
pablo@build:~/deepstream-nvdsanalytics$ apt list --installed *nvidia*
Listing... Done
libnvidia-cfg1-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
libnvidia-common-495/unknown,now 495.29.05-0ubuntu1 all [installed,automatic]
libnvidia-compute-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
libnvidia-container-tools/bionic,now 1.6.0~rc.2-1 amd64 [installed,automatic]
libnvidia-container1/bionic,now 1.6.0~rc.2-1 amd64 [installed,automatic]
libnvidia-decode-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
libnvidia-encode-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
libnvidia-extra-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
libnvidia-fbc1-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
libnvidia-gl-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
nvidia-compute-utils-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
nvidia-container-runtime/bionic,now 3.6.0~rc.2-1 amd64 [installed]
nvidia-container-toolkit/bionic,now 1.6.0~rc.2-1 amd64 [installed]
nvidia-dkms-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
nvidia-driver-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
nvidia-kernel-common-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
nvidia-kernel-source-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
nvidia-modprobe/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
nvidia-prime/bionic-updates,now 0.8.16~0.18.04.1 all [installed,automatic]
nvidia-settings/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
nvidia-utils-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
xserver-xorg-video-nvidia-495/unknown,now 495.29.05-0ubuntu1 amd64 [installed,automatic]
```

**Comment by caballeto** [comment] 2021-11-09 20:51
> For ubuntu 20 helped:
> 
> ```
> uname -a
> Linux ml-prod 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.3 LTS
> Release:	20.04
> Codename:	focal
> ```
> 
> * add experimental repo: `curl -s -L https://nvidia.github.io/nvidia-container-runtime/experimental/$distribution/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list`
> * `sudo apt-get update`
> * `sudo apt-get install -y nvidia-docker2`
> * `sudo systemctl restart docker`
> 
> source: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit

Big thanks, that worked!

**Comment by tgravescs** [comment] 2021-11-11 16:23
I had the same issue on ubuntu 18, the work around fixed it.  You might want to update the description on this.

**Comment by elezar** [comment] 2021-11-18 11:59
@dannf we have published the NVIDIA Container Toolkit 1.6.0 release to our stable package repositories. This means that the `nvidia-container-toolkit` package `1.6.0` is available with this fix. See the [release notes](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/release-notes.html#nvidia-container-toolkit-1-6-0)

Are you ok with closing this issue?

**Comment by dannf** [comment] 2021-11-18 15:48
On Thu, Nov 18, 2021 at 4:59 AM Evan Lezar ***@***.***> wrote:

> @dannf <https://github.com/dannf> we have published the NVIDIA Container
> Toolkit 1.6.0 release to our stable package repositories. This means that
> the nvidia-container-toolkit package 1.6.0 is available with this fix.
> See the release notes
> <https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/release-notes.html#nvidia-container-toolkit-1-6-0>
>
> Are you ok with closing this issue?
>
I am, thanks! As an aside, our server team made a suggestion of adding CI
that tests `n-c-r` against `runc` from git, implying that it would have
maybe surfaced this issue sooner.

  -dann

**Comment by javierchan** [comment] 2021-11-18 16:51
> @dannf we have published the NVIDIA Container Toolkit 1.6.0 release to our stable package repositories. This means that the `nvidia-container-toolkit` package `1.6.0` is available with this fix. See the [release notes](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/release-notes.html#nvidia-container-toolkit-1-6-0)
> 
> Are you ok with closing this issue?

Is this FIX also published for Jetson devices??, thank you for this effort.

**Comment by elezar** [comment] 2021-11-18 18:39
@javierchan we are working on a fix for Jetson devices and will get it out as soon as possible. Our current timeline is targeting the end of next week at the latest.

**Comment by elezar** [comment] 2021-11-25 14:10
We have published the `nvidia-container-toolkit=1.7.0~rc.1-1` to our experimental repositories that includes a fix for this on Jetson devices. Note that this is a release candidate which we will continue testing on our end and will push out fixes as further release candidates if required.

cc @javierchan @girgink @jgardynik we

**Comment by elezar** [comment] 2021-11-25 20:11
@dannf with regards to:

> I am, thanks! As an aside, our server team made a suggestion of adding CI
> that tests `n-c-r` against `runc` from git, implying that it would have
> maybe surfaced this issue sooner.

is this something that you need action on our end for, or do you mean that we need to add tests for this specifically? Feel free to open a new issue with more details so that we can do that.

**Comment by javierchan** [comment] 2021-11-26 16:53
> 

Thank you @elezar, so with this is supposed to be in experimental repo, according to process that we can follow i have a message -  # Unsupported distribution! - so, its another repo where this RC is pushed??

**Comment by elezar** [comment] 2021-11-29 08:20
@javierchan how are you setting up the experimental repo? In this case it's generally important what your `distribution` is as per the steps followed in https://github.com/NVIDIA/nvidia-container-runtime/issues/157#issuecomment-964386552

**Comment by javierchan** [comment] 2021-11-29 15:48
> * curl -s -L https://nvidia.github.io/nvidia-container-runtime/experimental/$distribution/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list

Yes, just like described steps on #157 

curl -s -L https://nvidia.github.io/nvidia-container-runtime/experimental/$distribution/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list
# Unsupported distribution!
# Check https://nvidia.github.io/nvidia-container-runtime

➜  ~ uname -a
Linux agx-xavier 4.9.201-tegra #1 SMP PREEMPT Wed May 5 09:32:25 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

**Comment by javierchan** [comment] 2021-11-29 15:49
> @javierchan how are you setting up the experimental repo? In this case it's generally important what your `distribution` is as per the steps followed in [#157 (comment)](https://github.com/NVIDIA/nvidia-container-runtime/issues/157#issuecomment-964386552)

Yes, just like described steps on #157 

curl -s -L https://nvidia.github.io/nvidia-container-runtime/experimental/$distribution/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list
# Unsupported distribution!
# Check https://nvidia.github.io/nvidia-container-runtime

➜  ~ uname -a
Linux agx-xavier 4.9.201-tegra #1 SMP PREEMPT Wed May 5 09:32:25 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

**Comment by elezar** [comment] 2021-11-29 15:57
What is the value of `$distrubution` in this case (`echo $distribution`)? Does it work if you explicitly use `ubuntu18.04`?

That is `https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/nvidia-container-runtime.list`

**Comment by javierchan** [comment] 2021-11-29 16:14
> https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/nvidia-container-runtime.list

Perfect, sorry not validate $distrubution value before,  (echo $distribution) is empty . . . 

So, i use: 
curl -s -L  https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list

Add the keys:

curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | sudo apt-key add -

And do an update / dist upgrade.

Thank you!

**Comment by elezar** [comment] 2021-12-01 11:28
The `1.7.0-rc.1` packages have been promoted to GA and are available from our `stable` repositories. This addresses this issue on Jetson devices.

See https://github.com/NVIDIA/nvidia-container-toolkit/releases/tag/v1.7.0

**Comment by dannf** [comment] 2021-12-01 21:49
> @dannf with regards to:
> 
> > I am, thanks! As an aside, our server team made a suggestion of adding CI
> > that tests `n-c-r` against `runc` from git, implying that it would have
> > maybe surfaced this issue sooner.
> 
> is this something that you need action on our end for, or do you mean that we need to add tests for this specifically? Feel free to open a new issue with more details so that we can do that.

Done as #160

**Comment by florian-fischer-swarm** [comment] 2021-12-06 16:38
Out of curiosity: Is this also going to show up on
https://repo.download.nvidia.com/jetson/
in the future, or is https://nvidia.github.io/libnvidia-container/ the canonical package source?

On jetson l4t this is not included as package source per default.

**Comment by elezar** [comment] 2021-12-07 08:35
@florian-fischer-swarm the packages should be picked up in an upcoming jetpack update and published to the `jetson` repos. The `https://nvidia.github.io/libnvidia-container/` is the repository to which we publish the components of the NVIDIA container stack for all supported platforms and will generally be ahead of the jetson versions.

> On jetson l4t this is not included as package source per default.

Up until the `1.7.0` release that contains this fix for Jetson the packages published to the non-jetson repo were not compatible with Jetson. Since this has now changed, we could look at including the repositories in the `l4t` configuration. With that said, we are also planning to migrate away from github pages to `download.nvidia.com` and it may be better to wait until that is complete.

**Comment by klueska** [comment] 2021-12-09 10:05
I am closing this issue now as multiple reports above have confirmed that the issue is now resolved (both on server and jetson systems).

**Closed by klueska** 2021-12-09 10:05 UTC

**Comment by florian-fischer-swarm** [comment] 2021-12-09 11:51
@elezar Thanks for the clarification!

**Comment by cpuguy83** [comment] 2022-01-05 21:27
So the fix for this was just bumping the runtime spec? No other changes?

**Comment by elezar** [comment] 2022-01-10 11:48
@cpuguy83 yes. The fields related to modifying the return code for certain syscalls were not present in the version of the spec that we were pinned to. This meant that these fields were dropped when loading, modifying (to inject our prestart hook), and saving the spec before execing runc. Updating the spec means that this information is not lost and we are working on a more robust mechanism for injection so as to avoid further issues such as this in future.

**Comment by cpuguy83** [comment] 2022-01-10 19:16
@elezar Thank you!

I did trace this down into libseccomp and realized it was returning EPERM due to a rule having the same effect as the default policy... which happens because docker/containerd now have a rule for `clone3` which set `errnoRet` to `ENOSYS`, which is the field that was added to the runtime spec that was getting dropped causing the rule to error out like that.
